name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint commit messages
      if: github.event_name == 'pull_request'
      uses: wagoid/commitlint-github-action@v6

    - name: Run linting
      run: npm run lint

    - name: Check formatting
      run: npm run format:check

    - name: Build project
      run: npm run build

    - name: Run tests with coverage
      run: npm run cover

    - name: Display coverage summary
      run: npx nyc report --reporter=text-summary

    - name: Run comparison benchmarks
      run: |
        echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "### Node.js ${{ matrix.node-version }} - Performance vs Competing Libraries" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        timeout 300s npm run benchmark:comparison 2>&1 | tee benchmark-output.txt || echo "Benchmark failed or timed out"
        cat benchmark-output.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage to artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == 20
      with:
        name: coverage-report
        path: |
          coverage.lcov
          .nyc_output/