name: Commitlint

on:
  pull_request:
    branches: [ main, master ]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v6